import pygame

GROUND = """
    #####
    # 2 #
    #   #
    # 1 #
    #####
"""

# POSITION
PLAYER_ONE_POSITION = '1'
PLAYER_TWO_POSITION = '2'
WALL = '#'

# REWARDS
REWARD_WIN = 100
REWARD_LOSE = -100
REWARD_BORDER = -10
REWARD_NOTHING = -20
REWARD_GET_HIT = -45
REWARD_GET_HEAVY_HIT = -30
REWARD_DIRECT_HIT = 10
REWARD_DIRECT_HEAVY_HIT = 30
REWARD_BREAK_BLOCK = 20
REWARD_BLOCKED_HIT = 5
RUN_IN_OPPONENT = -15
REWARD_RETREAT = -1
REWARD_APPROACH = 5
REWARD_MISS = -40
REWARD_HIT_IN_BLOCK = -10

#ACTIONS
LEFT = 'LEFT'
RIGHT = 'RIGHT'
UP = 'UP'
DOWN = 'DOWN'
ATT_LEFT = 'ATT_LEFT'
ATT_RIGHT = 'ATT_RIGHT'
HEAVY_ATT_LEFT = 'H_ATT_LEFT'
HEAVY_ATT_RIGHT = 'H_ATT_RIGHT'
BLOCK_LEFT = 'BLOCK_LEFT'
BLOCK_RIGHT = 'BLOCK_RIGHT'
NOTHING = 'NOTHING'

ACTIONS = [
    LEFT,
    RIGHT,
    UP,
    DOWN,
    NOTHING,
    ATT_LEFT,
    ATT_RIGHT,
    HEAVY_ATT_LEFT,
    HEAVY_ATT_RIGHT,
    BLOCK_LEFT,
    BLOCK_RIGHT
]

#DAMAGE
HIT_DMG = 5
HEAVY_HIT_DMG = 10
HEAVY_HIT_ON_BLOCK_DMG = 7

