import pygame

GROUND = """
    #####
    # 2 #
    #   #
    # 1 #
    #####
"""

# ASSETS
background = pygame.image.load("assets/ring_de_box.PNG")

# POSITION
PLAYER_ONE_POSITION = '1'
PLAYER_TWO_POSITION = '2'

# REWARDS
REWARD_WIN = 100
REWARD_LOSE = -100
REWARD_BORDER = -10
REWARD_NOTHING = -1
REWARD_GET_HIT = -5
REWARD_DIRECT_HIT = 10
REWARD_BLOCKED_HIT = 5

#ACTIONS
LEFT = 'LEFT'
RIGHT = 'RIGHT'
UP = 'UP'
DOWN = 'DOWN'
ATT_LEFT = 'ATT_LEFT'
ATT_RIGHT = 'ATT_RIGHT'
HEAVY_ATT_LEFT = 'H_ATT_LEFT'
HEAVY_ATT_RIGHT = 'H_ATT_RIGHT'
BLOCK_LEFT = 'BLOCK_LEFT'
BLOCK_RIGHT = 'BLOCK_RIGHT'
NOTHING = 'NOTHING'

ACTIONS = [
    LEFT,
    RIGHT,
    NOTHING,
    ATT_LEFT,
    ATT_RIGHT,
    HEAVY_ATT_LEFT,
    HEAVY_ATT_RIGHT,
    BLOCK_LEFT,
    BLOCK_RIGHT
]

#DAMAGE
HIT_DMG = 5
HEAVY_HIT_DMG = 10

